name: promethyl
channels:
  - conda-forge
  - bioconda
  - nanoporetech
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - pyranges
  - pyyaml
  - pip
  - bedtools
  - modkit
  - samtools
  - jinja2
